# Utility functions (e.g., helper functions like should_avoid_text,

FILTER_OUT = [
    "senior",
    "middle",
    "lead",
    "night",
    "arendaja",
    "vanemarendaja",
    "veebiarendaja",
    "testija",
    "projektijuht",
    "security",
    "director",
    "accountant",
    "legal",
    "risk",
    "therapist",
    "autonoomsete",
    "sõidukite",
    "seadmete",
    "valdkonna",
    "vanemteadur",
    "küberturbe",
    "projektijuht",
    "majandustarkvara",
    "kaubanduse",
    "logistika",
    "analüütik",
    "konsultant",
    "tooteomanik",
    "it-juht",
    "konsultant",
    "elektrimontaažilukksepp",
    "swedish",
    "spanish",
    "shifts",
    "maastiku",
    "tegija",
    "ios",
    "tarkvarainsener",
]
ALLOW_ONLY = [
    "analyst",
    "analiste",
    "аналитик",
    "analise",
    "аналитик/system",
    "analysis",
    "аналитика",
    "аналитики",
    "данных",
    "аналитик(начинающий)",
    "backend",
    "backend-разработчик",
    "бизнес-аналитик",
    "бизнес-аналитика",
    "бизнес-аналитик/аналитик",
    "back-end",
    "data",
    "data-science-специалист",
    "digital",
    "developer",
    "интерфейс",
    "инженер-программист",
    "manual",
    "open",
    "программист",
    "искусственным",
    "программированию",
    "программирование",
    "python-разработчик",
    "qa",
    "рекрутер",
    "английском",
    "исполнителей",
    "ручной",
    "разметчик",
    "системы",
    "системный",
    "системный/бизнес",
    "системный/специалист",
    "специалист-аналитик",
    "анализу",
    "аналитике",
    "тестировщик",
    "software",
    "intern",
    "frontend",
    "developpeur",
    "stage",
    "sw",
    "visualization",
    "sw/qa",
    "technical",
    "consultant",
    "french",
    "ux-исследователя",
    "virtual",
]


def should_avoid_text(text):
    """
    Check if the vacancy name contains any keywords to avoid.
    Args:
        name: The name of the vacancy.
        avoid_keywords: A list of keywords to avoid.
    Returns:
        True if the name contains any avoid keywords, otherwise False.
    """
    return any(keyword in text.lower() for keyword in FILTER_OUT)
